### ISSUE TITLE
"ensure CRDs are installed first"

### ISSUE THREAD

**Issue by nordge1** [samip5/k8s-cluster#1645]
Admittedly, I am a noob to microk8s & kustomize. 
I am trying to build your repo and I get the following. Is this a bug or am I applying this incorrectly?
Any help would be appreciated.

`user@k8serv1:~/k8s-cluster/k8s/media/apps$ microk8s kubectl apply -k media  

namespace/media unchanged
resource mapping not found for name: "cluster-apps-bazarr" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-cross-seed" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-media-index" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-qbit" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-qbittorrent" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-qbittorrent-tools" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-radarr" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-sonarr" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first
resource mapping not found for name: "cluster-apps-tautulli" namespace: "flux-system" from "media": no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1"
ensure CRDs are installed first`

**Comment by samip5** [comment]
You're applying it incorrectly as most of my repo depends on Flux custom resources, so without Flux installed, it's going to be a huge pain.

I also don't provide support so I'm closing this as won't fix.
